### PR TITLE
added files

### PR DESCRIPTION
**Pull request by jmfergeau**
title ☝️

### CODE REVIEW

**Comment by RobLoach** [comment]
:fire:

**Comment by RobLoach** [comment]
Some of these look pretty grainy. Were they up-scaled to 512px wide? Usually if they're smaller than 512px, they're kept as is.

For example.....

Rampage

**Comment by jmfergeau** [comment]
Didn't had choice for that one. Still looking for better but no chance yet.

**Comment by jmfergeau** [comment]
nvm, i found a better one using other terms. Gonna make a new commit in a few mins.

**Comment by RobLoach** [comment]
Seeing a black border around the snaps? For example...



Usually we avoid having the black borders around the images. If it ends up being less than 512px because of it, that's okay.

**Pull request merged**
